urlwordlist/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('core.views',
    url(r'^/?$', 'display_home', name='home'),
    url(r'^scan/?$', 'display_scan_form', name='scan'),
    url(r'^results/(?P<result_id>[0-9]+)/?$', 'display_scan_result', name='result'),
    url(r'^tests/(?P<test_id>[0-9]+)/?$', 'display_test', name='test'),
)

urlwordlist/urlwordlist/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'urlwordlist.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'', include('core.urls', namespace='core', app_name='core')),
)

urlwordlist/core/models.py
"""
Data models for the application.
"""
from django.db import models

class ScanResult(models.Model):
    """
    Entity representing a single URL submission and scan event.
    """
    url = models.URLField(max_length=1000)
    created_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = 'core'

    def top_word(self):
        """
        Returns the single most prevalent word for this scan result.
        """
        return self.words.order_by('-num_occurrences').first()
    
class ScanResultWord(models.Model):
    """
    Entity representing one of the N top words for a scan event.
    """
    result = models.ForeignKey('ScanResult', related_name='words', related_query_name='word')
    word = models.CharField(max_length=50)
    num_occurrences = models.IntegerField()

    class Meta:
        app_label = 'core'

urlwordlist/core/forms.py
"""
Represents an HTML form and provides some under-the-covers validation
by virtue of picking appropriate field types.
"""
from django import forms

class ScanForm(forms.Form):
    url = forms.URLField(label='URL of Web Page to Scan', max_length=1000)

urlwordlist/core/views.py
"""
Processes incoming HTTP requests, as directed by urls.py.
"""
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader, RequestContext, TemplateDoesNotExist
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
import logging
from core.models import ScanResult
from core.forms import ScanForm
from core.scanner import scan_url, ScanError

logger = logging.getLogger(__name__)

def display_home(request):
    """
    displays a list of previously-scanned URLS, along with the most-repeated word for each.
    """
    context_vars = {}
    context_vars['results'] = ScanResult.objects.all().order_by('-created_dt')
    return render(request, 'home.html', context_vars)

def display_scan_form(request):
    """
    displays and handles input from a form allowing the user to enter a URL to scan.
    """
    if request.method == 'POST':
        form = ScanForm(request.POST)
        scan_result = None
        if form.is_valid():
            try:
                scan_result = ScanResult.objects.get(url__iexact=form.cleaned_data['url'])
            except ObjectDoesNotExist:
                try:
                    top_words = scan_url(form.cleaned_data['url'], settings.NUM_WORDS_PER_URL)
                except ScanError as e:
                    logger.exception(e)
                    form.add_error(None, e.message)
                else:
                    scan_result = ScanResult(url=form.cleaned_data['url'])
                    scan_result.save()
                    for word, num_occurrences in top_words:
                        scan_result.words.create(word=word, num_occurrences=num_occurrences)
        else:
            logger.debug('Scan form submission errors: {}'.format(form.errors))
        if scan_result:
            return HttpResponseRedirect(reverse('core:result', kwargs={'result_id': scan_result.id}))
    else:
        form = ScanForm()
    return render(request, 'scan.html', {'form': form})

def display_scan_result(request, result_id):
    """
    displays the top ten words for a scanned URL, along with the number of appearances for each.
    """
    context_vars = {}
    try:
        context_vars['result'] = ScanResult.objects.get(id=result_id)
    except ObjectDoesNotExist as e:
        logger.exception(e)
        raise Http404
    return render(request, 'result.html', context_vars)

def display_test(request, test_id):
    """
    displays test web pages.
    """
    try:
        template = loader.get_template('test_{}.html'.format(test_id))
    except TemplateDoesNotExist as e:
        logger.exception(e)
        raise Http404
    return HttpResponse(template.render(RequestContext(request)))

urlwordlist/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/static/css/custom.css">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <title>{% block title %}{% endblock title %} - URLWordList</title>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'core:home' %}">URLWordList</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    {% block nav %}
                    <ul class="nav navbar-nav">
                        <li{% if site_section = 'home' %} class="active"{% endif %}><a href="{% url 'core:home' %}">Home</a></li>
                        <li{% if site_section = 'scan' %} class="active"{% endif %}><a href="{% url 'core:scan' %}">Scan URL</a></li>
                    </ul>
                    {% endblock nav %}
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="content">
                {% block content %}{% endblock content %}
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

urlwordlist/core/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block nav %}
    {% with 'home' as site_section %}
        {{ block.super }}
    {% endwith %}
{% endblock nav %}
{% block content %}
                <h3>Scan History <small>URLs Previously Scanned</small></h3>
                {% if results %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>URL</th>
                                <th>Date/Time Scanned</th>
                                <th>Top Word</th>
                                <th>Num Occurrences</th>
                            </tr>
                        </thead>
                        <tbody>
                    {% for result in results %}
                            <tr>
                                <td><a href="{% url 'core:result' result_id=result.id %}" title="View Results">{{ result.url }}</a></td>
                                <td>{{ result.created_dt }}</td>
                                <td>{{ result.top_word.word }}</td>
                                <td>{{ result.top_word.num_occurrences }}</td>
                            </tr>
                    {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                No URLs scanned yet.  <a href="{% url 'core:scan' %}" title="Scan a URL">Click here to scan one!</a>
                {% endif %}
{% endblock content %}

urlwordlist/core/templates/result.html
{% extends "base.html" %}
{% block title %}Scan Results{% endblock title %}
{% block nav %}
    {% with 'scan' as site_section %}
        {{ block.super }}
    {% endwith %}
{% endblock nav %}
{% block content %}
                <h3>Scan Results</h3>
                <p class="lead">URL Scanned: <a href="{{ result.url }}" target="_blank">{{ result.url }}</a></p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Top Words</th>
                            <th>Num Occurrences</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for word in result.words.all %}
                            <tr>
                                <td>{{ word.word }}</td>
                                <td>{{ word.num_occurrences }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <em>Scanned on {{ result.created_dt|date:"r" }}</em>
{% endblock content %}

urlwordlist/core/templates/scan.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block nav %}
    {% with 'scan' as site_section %}
        {{ block.super }}
    {% endwith %}
{% endblock nav %}
{% block content %}
    <h3>Scan a URL</h3>
    {% if form.errors or form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        <strong>ERRORS</strong>
        <button type="button" class="close" data-dismiss="alert">X</button>
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
        {% for field in form %} 
            {% if field.errors %}
            <li>{{ field.label }}: {{ field.errors|striptags }}</li>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    <form role="form" action="{% url 'core:scan' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="url">{{ form.url.label }}</label>
            <input type="url" class="form-control" id="url" name="url" placeholder="Example: https://www.example.com/">
        </div>
        <button type="submit" class="btn btn-default">Scan URL</button>
    </form>
{% endblock content %}

urlwordlist/core/templates/test_1.html
<html>
    <head>
        <title>This</title>
    </head>
    <body>is a test.</body>
</html>

urlwordlist/core/templates/test_2.html
<html>
    <body>Derp Derpity Derp blazerp derp blazerp</body>
</html>

urlwordlist/core/templates/test_4.html
<html>
    <body>


    
    </body>
</html>